export const estadosMexico = [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila",
    "Colima",
    "CDMX",
    "Durango",
    "Estado de México",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas",
  ];

export const abreviaturasEstados = {
    "Aguascalientes": "Ags",
    "Baja California": "BC",
    "Baja California Sur": "BCS",
    "Campeche": "Camp",
    "Chiapas": "Chis",
    "Chihuahua": "Chih",
    "Coahuila": "Coah",
    "Colima": "Col",
    "CDMX": "CDMX",
    "Durango": "Dgo",
    "Estado de México": "Edomex",
    "Guanajuato": "Gto",
    "Guerrero": "Gro",
    "Hidalgo": "Hgo",
    "Jalisco": "Jal",
    "Michoacán": "Mich",
    "Morelos": "Mor",
    "Nayarit": "Nay",
    "Nuevo León": "NL",
    "Oaxaca": "Oax",
    "Puebla": "Pue",
    "Querétaro": "Qro",
    "Quintana Roo": "QR",
    "San Luis Potosí": "SLP",
    "Sinaloa": "Sin",
    "Sonora": "Son",
    "Tabasco": "Tab",
    "Tamaulipas": "Tamps",
    "Tlaxcala": "Tlax",
    "Veracruz": "Ver",
    "Yucatán": "Yuc",
    "Zacatecas": "Zac",
  };